export const JURONG_WEST_AVE_1_BLK_536_BUS_STOP_CODE = 28531;
export const JURONG_WEST_AVE_1_BLK_454_BUS_STOP_CODE = 28409;
export const JURONG_WEST_AVE_1_BLK_551_BUS_STOP_CODE = 28541;

export const FAVORITE_BUS_STOP_LOCAL_STORAGE_KEY =
  "FAVORITE_BUS_STOP_LOCAL_STORAGE_KEY";

export enum TabName {
  Favorites = "FAVORITES",
  Nearest = "NEAREST",
}

export const GET_BUS_STOPS_PAGE_SIZE = 500;
